package bmo.command;

import bmo.exception.BmoException;
import bmo.storage.Storage;
import bmo.task.TaskList;
import bmo.ui.Ui;

/**
 * Represents a command which exits the program. A <code>ByeCommand</code> object
 * corresponds to a command which stores the BYE CommandWord e.g., <code>CommandWord.BYE</code>
 */
public class ByeCommand extends Command {

    public ByeCommand() {
        super(CommandWord.BYE, true);
    }

    /**
     * Displays the list of tasks to the user.
     * Saves the list of tasks in the save file.
     * Returns the messages generated when executing the command.
     * If the lines cannot be written to the save file,
     * a custom exception is thrown.
     *
     * @param taskList The list of tasks to be saved.
     * @param ui The user interface object.
     * @param storage The storage object.
     * @return The messages generated by the command.
     * @throws BmoException If lines cannot be written to the save file.
     */
    @Override
    public String execute(TaskList taskList, Ui ui, Storage storage) throws BmoException {
        // Store lines of text to be stored
        String saveText = taskList.saveString();

        // Display lines of text to be stored to user
        String messages = ui.showSaveMessage(saveText);

        // Store the lines in the save file
        storage.save(saveText);

        return messages;
    }
}
