package bmo.command;

import bmo.exception.BmoException;
import bmo.storage.Storage;
import bmo.task.TaskList;
import bmo.ui.Ui;

/**
 * Represents a command created from a line of user input. A <code>Command</code> object
 * corresponds to any command represented by a CommandWord e.g., <code>CommandWord.LIST</code>
 */
public abstract class Command {
    protected CommandWord commandWord;

    Command(CommandWord commandWord) {
        this.commandWord = commandWord;
    }

    public CommandWord getCommandWord() {
        return this.commandWord;
    }

    /**
     * Executes the command on the main program parts.
     * Returns the messages generated when executing the command.
     * A custom exception may be thrown.
     *
     * @param taskList The list of tasks to be saved.
     * @param ui The user interface object.
     * @param storage The storage object.
     * @return The messages generated by the command.
     * @throws BmoException If an unexpected event occurs.
     */
    public abstract String execute(TaskList taskList, Ui ui, Storage storage) throws BmoException;
}
