package bmo.command;

import bmo.storage.Storage;
import bmo.task.TaskList;
import bmo.ui.Ui;

/**
 * Represents a command which returns a list of tasks which contain the given keyword.
 * A <code>FindCommand</code> object corresponds to a command which stores the
 * FIND CommandWord e.g., <code>CommandWord.FIND</code>, and a keyword e.g.,
 * <code>book</code>
 */
public class FindCommand extends Command {

    private String keyword;

    /**
     * Initializes a <code>FindCommand</code> object which stores command parameters
     * representing the keyword to be matched.
     *
     * @param keyword The String containing a keyword to be matched
     */
    public FindCommand(String keyword) {
        super(CommandWord.FIND, false);
        this.keyword = keyword;
    }

    /**
     * Performs an action on the TaskList to display a filtered list of tasks
     * which contain the keyword.
     * Returns the messages generated when executing the command.
     *
     * @param taskList a TaskList object with the full list of tasks
     * @param ui a user interface object
     * @param storage a storage object
     * @return The messages generated by the command.
     */
    @Override
    public String execute(TaskList taskList, Ui ui, Storage storage) {
        // Get a TaskList consisting of tasks which contain the keyword
        TaskList filteredTasks = taskList.listMatchingTasks(this.keyword);

        // List the tasks inside the new TaskList
        return ui.showMatchingTasks(filteredTasks);
    }
}
