package bmo.command;

import bmo.parser.CommandWord;
import bmo.storage.Storage;
import bmo.task.Task;
import bmo.task.TaskList;
import bmo.ui.Ui;

/**
 * Represents a command which marks a task in the list of tasks as not done.
 * A <code>UnmarkCommand</code> object corresponds to a command which stores the
 * UNMARK CommandWord e.g., <code>CommandWord.UNMARK</code>, and an integer which
 * represents the index of task in the list of tasks to be marked as not done e.g., 2
 */
public class UnmarkCommand extends Command {

    private int index;

    /**
     * Initializes an <code>UnmarkCommand</code> object which stores command parameters
     * representing the index of the task list to be marked as not done.
     *
     * @param index The index corresponding to the task to be marked as not done
     */
    public UnmarkCommand(int index) {
        super(CommandWord.UNMARK, false);
        this.index = index;
    }

    /**
     * Marks a task corresponding to the index in the task list as not done.
     * Displays the information to the user.
     * Returns the messages generated when executing the command.
     *
     * @param taskList The list of tasks to be saved.
     * @param ui The user interface object.
     * @param storage The storage object.
     * @return The messages generated by the command.
     */
    @Override
    public String execute(TaskList taskList, Ui ui, Storage storage) {
        Task unmarkTask = taskList.unmarkTask(this.index);

        return ui.showUnmarkMessage(unmarkTask);
    }
}
