package bmo.task;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.time.LocalDateTime;
import java.util.List;

import org.junit.jupiter.api.Test;

import bmo.parser.TaskListParser;

/**
 * Represents the test class for the <code>TaskList</code> class. A <code>TaskListTest</code>
 * object stores the test cases which perform operations on <code>TaskList</code> objects.
 */
public class TaskListTest {
    /**
     * Add a <code>Todo</code> object to a <code>TaskList</code> object
     *
     * @result Task will be stored in the TaskList without any errors,
     *         and it is reflected in Task.toString()
     */
    @Test
    public void addTask_todoTask() {
        TaskList taskList = new TaskList();
        Task task = new Todo("read book");
        taskList.addTask(task);
        assertEquals("[T][ ] read book", taskList.toString());
    }

    /**
     * Add a <code>Deadline</code> object to a <code>TaskList</code> object
     *
     * @result Task will be stored in the TaskList without any errors,
     *         and it is reflected in Task.toString()
     */
    @Test
    public void addTask_todoDeadline() {
        TaskList taskList = new TaskList();
        LocalDateTime due = LocalDateTime.parse("05-03-2026 1200",
                TaskListParser.INPUT_FORMATTER);
        Task task = new Deadline("return book", due);
        taskList.addTask(task);
        assertEquals("[D][ ] return book (by: Mar 5 2026 1200)", taskList.toString());
    }

    /**
     * Add an <code>Event</code> object to a <code>TaskList</code> object
     *
     * @result Task will be stored in the TaskList without any errors,
     *         and it is reflected in Task.toString()
     */
    @Test
    public void addTask_todoEvent() {
        TaskList taskList = new TaskList();
        LocalDateTime start = LocalDateTime.parse("05-03-2026 1300",
                TaskListParser.INPUT_FORMATTER);
        LocalDateTime end = LocalDateTime.parse("06-03-2026 1400",
                TaskListParser.INPUT_FORMATTER);
        Task task = new Event("project meeting", start, end);
        taskList.addTask(task);
        assertEquals("[E][ ] project meeting (from: Mar 5 2026 1300, to: Mar 6 2026 1400)", taskList.toString());
    }

    /**
     * Add multiple <code>Task</code> objects to a <code>TaskList</code> object
     * and list them.
     *
     * @result The tasks will be stored in the TaskList without any errors,
     *         and they are listed in the order which they were stored.
     */
    @Test
    public void listTasks_subclassTasks_success() {
        LocalDateTime due = LocalDateTime.parse("05-03-2026 1200",
                TaskListParser.INPUT_FORMATTER);
        LocalDateTime start = LocalDateTime.parse("05-03-2026 1300",
                TaskListParser.INPUT_FORMATTER);
        LocalDateTime end = LocalDateTime.parse("06-03-2026 1400",
                TaskListParser.INPUT_FORMATTER);

        Task task1 = new Todo("read book");
        Task task2 = new Deadline("return book", due);
        Task task3 = new Event("project meeting", start, end);
        List<Task> tasks = List.<Task>of(task1, task2, task3);
        TaskList taskList = new TaskList(tasks);

        assertEquals("1. [T][ ] read book\n"
                + "2. [D][ ] return book (by: Mar 5 2026 1200)\n"
                + "3. [E][ ] project meeting (from: Mar 5 2026 1300, to: Mar 6 2026 1400)",
                taskList.listTasks());
    }

    /*
    The following methods were generated by Gemini CLI.
     */
    @Test
    public void isEmpty_success() {
        TaskList taskList = new TaskList();
        assertEquals(true, taskList.isEmpty());
        taskList.addTask(new Todo("read book"));
        assertEquals(false, taskList.isEmpty());
    }

    @Test
    public void getTotal_success() {
        TaskList taskList = new TaskList();
        assertEquals(0, taskList.getTotal());
        taskList.addTask(new Todo("read book"));
        assertEquals(1, taskList.getTotal());
    }

    @Test
    public void isInRange_success() {
        TaskList taskList = new TaskList();
        taskList.addTask(new Todo("read book"));
        assertEquals(true, taskList.isInRange(1));
        assertEquals(false, taskList.isInRange(0));
        assertEquals(false, taskList.isInRange(2));
    }

    @Test
    public void markTask_success() {
        TaskList taskList = new TaskList();
        taskList.addTask(new Todo("read book"));
        taskList.markTask(1);
        assertEquals("[T][X] read book", taskList.toString());
    }

    @Test
    public void unmarkTask_success() {
        TaskList taskList = new TaskList();
        taskList.addTask(new Todo("read book"));
        taskList.markTask(1);
        taskList.unmarkTask(1);
        assertEquals("[T][ ] read book", taskList.toString());
    }

    @Test
    public void deleteTask_success() {
        TaskList taskList = new TaskList();
        taskList.addTask(new Todo("read book"));
        taskList.deleteTask(1);
        assertEquals(0, taskList.getTotal());
    }

    @Test
    public void listMatchingTasks_success() {
        TaskList taskList = new TaskList();
        taskList.addTask(new Todo("read book"));
        taskList.addTask(new Todo("study math"));
        TaskList matchingTasks = taskList.listMatchingTasks("read");
        assertEquals(1, matchingTasks.getTotal());
        assertEquals("[T][ ] read book", matchingTasks.toString());
    }

    @Test
    public void saveString_success() {
        TaskList taskList = new TaskList();
        taskList.addTask(new Todo("read book"));
        assertEquals("T | 0 | read book", taskList.saveString());
    }
}
