package bmo.task;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

/**
 * Represents the test class for the <code>Task</code> class. A <code>TaskTest</code>
 * object stores the test cases which perform operations on <code>Task</code> objects.
 */
public class TaskTest {
    /**
     * Mark a newly created task as done.
     *
     * @result Task will be marked as done without any errors,
     *         and it is reflected in Task.toString()
     */
    @Test
    public void markAsDone_newTask() {
        Task task = new Task("read book");
        task.markAsDone();
        assertEquals("[X] read book", task.toString());
    }

    /**
     * Mark an already marked task as done.
     *
     * @result Task will remain marked as done without any errors,
     *         and it is reflected in Task.toString()
     */
    @Test
    public void markAsDone_markedTask() {
        Task task = new Task("read book");
        task.markAsDone();
        task.markAsDone();
        assertEquals("[X] read book", task.toString());
    }

    /**
     * Mark a newly created task as not done.
     *
     * @result Task will remain marked as not done without any errors,
     *         and it is reflected in Task.toString()
     */
    @Test
    public void markAsNotDone_newTask() {
        Task task = new Task("read book");
        task.markAsNotDone();
        assertEquals("[ ] read book", task.toString());
    }

    /**
     * Mark an already marked task as not done.
     *
     * @result Task will be marked as not done without any errors,
     *         and it is reflected in Task.toString()
     */
    @Test
    public void markAsNotDone_markedTask() {
        Task task = new Task("read book");
        task.markAsDone();
        task.markAsNotDone();
        assertEquals("[ ] read book", task.toString());
    }

    /*
    The following methods were generated by Gemini CLI.
     */
    @Test
    public void saveString_success() {
        Task task = new Task("read book");
        assertEquals("0 | read book", task.saveString());
        task.markAsDone();
        assertEquals("1 | read book", task.saveString());
    }

    @Test
    public void hasFullMatch_success() {
        Task task = new Task("Read Book!");
        assertEquals(true, task.hasFullMatch("read book"));
        assertEquals(true, task.hasFullMatch("READ BOOK"));
        assertEquals(true, task.hasFullMatch("readbook"));
        assertEquals(false, task.hasFullMatch("write book"));
    }

    @Test
    public void hasPartialMatch_success() {
        Task task = new Task("Read Book!");
        assertEquals(true, task.hasPartialMatch("r"));
        assertEquals(true, task.hasPartialMatch("R"));
        assertEquals(true, task.hasPartialMatch("read"));
        assertEquals(false, task.hasPartialMatch("w"));
    }
}
